//@url = http://localhost:55320
//@url = http://20.86.126.74/flashcards
@url = https://jm-flashcards.azurewebsites.net
@email = janusz@januszmarcinik.pl
@password = zaq1@WSX
@deckName = Azure

### Check whether API is healthy
GET {{url}} HTTP/1.1

### Register user
POST {{url}}/api/users HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}",
    "confirmPassword": "{{password}}"
}

### Login request to get token

# @name login
POST {{url}}/api/auth HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### Create deck
POST {{url}}/api/decks HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "name": "{{deckName}}",
    "description": ""
}

### Get created deck
GET {{url}}/api/decks/{{deckName}} HTTP/1.1
Authorization: Bearer {{login.response.body.token}}

### Create sample card in given deck
POST {{url}}/api/decks/{{deckName}}/cards HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "question": "<p>Testowa karta</p>",
    "answer": "<p>Jakaś odpowiedź</p>"
}

### Get cards in deck
GET {{url}}/api/decks/{{deckName}}/cards HTTP/1.1
Authorization: Bearer {{login.response.body.token}}