@url = http://localhost:55320
@email = janusz@januszmarcinik.pl
@password = zaq1@WSX
@deckName = OnPremises

###

# @name login
POST {{url}}/api/auth HTTP/1.1
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###

# @name createDeck
POST {{url}}/api/decks HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "name": "{{deckName}}",
    "description": ""
}

###

# @name createCard
POST {{url}}/api/decks/{{deckName}}/cards HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
    "question": "<p>Testowa karta</p>",
    "answer": "<p>Jakaś odpowiedź</p>"
}